### ISSUE TITLE
Pls don't ignore this big problem 

### ISSUE THREAD

**Issue by litylixx** [cupid-development/android_device_xiaomi_marble#1]
Why your tree and lineageos/calyxos roms doesn't support Dolby Atmos? I can’t use the device and, for example, listen to music without this function, without it the sound is much worse, Dolby Atmos makes the sound deeper and better, so why isn’t it in your ROM?

**Comment by Gelbpunkt** [comment]
Dolby Atmos is proprietary junk and not required for audio to function properly.
